# Generated by Django 5.0.2 on 2024-03-05 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gl_no', models.IntegerField(unique=True)),
                ('Bgl_no', models.CharField(max_length=255, unique=True)),
                ('Amount', models.PositiveIntegerField()),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('Items', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items_names', to='Notes.items_category')),
            ],
        ),
    ]
